import Conversation from "./../models/conversation.model.js";
import Message from "./../models/message.model.js";

export const sendMessage = async (req, res) => {
  try {
    const { message } = req.body;
    const { id: receiverId } = req.params;
    const senderId = req.user._id;

    let conversation = await Conversation.findOne({
      participants: { $all: [senderId, receiverId] },
    });

    if (!conversation) {
      conversation = await Conversation.create({
        participants: [senderId, receiverId],
      });
    }

    const newMessage = new Message({
      senderId: senderId,
      receiverId: receiverId,
      message: message,
    });

    if (newMessage) {
      conversation.messages.push(newMessage._id);
    }

    //run in parallel
    await Promise.all([conversation.save(), newMessage.save()]);

    res.status(201).send({ message: "Message Sent Successfully." });
  } catch (error) {
    console.log("sendMessage errors:- ", error.message);
    res.send({ error: "Internal Server Error." }).status(500);
  }
};

export const getMessage = async (req, res) => {
  try {
    const { id: userToChatId } = req.params;
    const senderId = req.user._id;

    const conversation = await Conversation.findOne({
      participants: { $all: [senderId, userToChatId] },
    }).populate("messages");

    if (!conversation) return res.status(200).json([]);

    const messages = conversation.messages;

    res.status(200).json(messages);
  } catch (error) {
    console.log("getMessage errors:- ", error.message);
    res.send({ error: "Internal Server Error." }).status(500);
  }
};
